### ISSUE TITLE
Accelerometer Module Development

### ISSUE THREAD

**Issue by NathanRoseCE** [ERFSEDS/common_modules#2]
Development of the accelerometer

**Comment by NathanRoseCE** [comment]
Add a heirarchical sheet to this module as specified in the Cerberus Github Guide

**Comment by ckeer0** [comment]
Please add a Readme. Specifics are in the Cerberus Github Guide

**Comment by NathanRoseCE** [comment]
@ckeer0 @fluffy-fury 
This package is TFLGA, I recommend switching off, though I am not hard set on this opinion

Minor Issues:
Digikey part number not in symbol
Power flags should be where the power comes into the circuit not just arbitrarily attatched

**Comment by ckeer0** [comment]
Issue closed
