### ISSUE TITLE
Barometer Development

### ISSUE THREAD

**Issue by NathanRoseCE** [ERFSEDS/common_modules#4]
Barometer Development

**Comment by ckeer0** [comment]
Please place silkscreen names next to each pin for easy identification. 
Place no connect symbol on pin four of the barometer

**Comment by NathanRoseCE** [comment]
Make sure you add a bottom ground pout to prevent potato chip boards, also it is a good practice

**Comment by NathanRoseCE** [comment]
Minor issues:
Pins 4 and 5 should be connected together
CLK should be changed to SCLK as is standard naming for SPI

**Comment by ckeer0** [comment]
Minor Issue:
Place power flags on 3V3 and GND pin to make ERC happy

**Comment by ckeer0** [comment]
Issue closed
