### ISSUE TITLE
Power Regulation

### ISSUE THREAD

**Issue by NathanRoseCE** [ERFSEDS/common_modules#5]
Circuit Voltage Regulation

**Comment by ckeer0** [comment]
Minor Issues: 

I can't for the life of me view your symbols. I think that it may just be me, but I just can't.

3.3V needs a power flag 

PCB has weird traces on the shield for the USB-C. 
Silkscreen needs some serious work. 

Functionally, it works, it's just the little things.

**Comment by NathanRoseCE** [comment]
Create one library that contains for each module and has all parts needed for the module
3.3V does not need a power flag @ckeer0 as the symbols will be power output and so a power flag will cause an output connected to output warning
Each module should only have the libary needed for itself

**Comment by ckeer0** [comment]
Issue closed
