### ISSUE TITLE
SD Card development

### ISSUE THREAD

**Issue by NathanRoseCE** [ERFSEDS/common_modules#8]
SD card development

**Comment by NathanRoseCE** [comment]
Schematic Issues:
Cap for SD card is in series not parallel
Routing
Unnecessary via by pin 8 and 9

**Comment by NathanRoseCE** [comment]
Minor issue:
MOSI made unnecessary antenna, where via is more appropriate

**Comment by ckeer0** [comment]
Issue Closed
